import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import Footer from "@/components/footer";
import { Providers } from "@/app/providers";
import { CartProvider } from "@/components/cart-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      {/* <body className={`${geistSans.variable} ${geistMono.variable}`}> */}
      <body className="flex min-h-full flex-col bg-white">
        <Providers>
          <CartProvider>
        <Navbar />
        {/* <main className="flex-grow container mx-auto px-4 py-8">{children}</main> */}
        <main className="flex-grow container mx-auto px-4 py-8">{children}</main>
        <Footer />
        </CartProvider>
        </Providers>
      </body>
    </html>
  );
}
